/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PerritosIcons {
  PerritosIcons._();

  static const _kFontFam = 'PerritosIcons';
  static const String? _kFontPkg = null;

  static const IconData Icon_User = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData Icon_Task = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData Icon_Smiley_Sad = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData Icon_Smiley_Happy = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData Icon_Send = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData Icon_Search = IconData(0xe905, fontFamily: _kFontFam);
  static const IconData Icon_Remove = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData Icon_Perritos = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData Icon_Home = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData Icon_Edit = IconData(0xe909, fontFamily: _kFontFam);
  static const IconData Icon_Dog = IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData Icon_Dog_Filled = IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData Icon_Date = IconData(0xe919, fontFamily: _kFontFam);
  static const IconData Icon_ArrowLeft = IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData Icon_Add = IconData(0xe91b, fontFamily: _kFontFam);
}
